image: "fedora:27"

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - bundle

build:linux:
  stage: build
  before_script:
  - dnf -y install gcc gcc-c++
  - dnf -y install cmake openssl-static.i686 boost-static.i686 zlib-static.i686 glibc-static.i686 libstdc++-static.i686 glibc-devel.i686 boost-devel openssl-devel
  script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make
  artifacts:
    paths:
    - build/rpc.ext.so

build:windows:
  stage: build
  before_script:
  - dnf -y install mingw32-gcc mingw32-gcc-c++
  - dnf -y install cmake mingw32-boost-static mingw32-zlib-static mingw32-openssl-static
  script:
  - mkdir build
  - cd build
  - CC=i686-w64-mingw32-gcc CXX=i686-w64-mingw32-g++ cmake -DTARGET=windows -DCMAKE_BUILD_TYPE=Release ..
  - make
  - cp /usr/i686-w64-mingw32/sys-root/mingw/bin/libwinpthread-1.dll .
  artifacts:
    paths:
    - build/rpc.ext.dll
    - build/libwinpthread-1.dll

bundle:windows:
  stage: bundle
  script:
  - cd build
  - mkdir -p bin
  - mkdir -p csgo/addons/sourcemod/extensions
  - cp libwinpthread-1.dll bin/
  - cp rpc.ext.dll csgo/addons/sourcemod/extensions/
  - zip -r rpc.zip bin/ csgo/
  artifacts:
    paths:
    - build/rpc.zip
  dependencies:
  - build:windows

bundle:linux:
  stage: bundle
  script:
  - cd build
  - mkdir -p csgo/addons/sourcemod/extensions
  - cp rpc.ext.so csgo/addons/sourcemod/extensions/
  - tar -cf rpc.tar.gz csgo/
  artifacts:
    paths:
    - build/rpc.tar.gz
  dependencies:
  - build:linux
