image: "fedora:27"

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - dnf -y install clang cmake openssl-static.i686 boost-static.i686 zlib-static.i686 glibc-static.i686 libstdc++-static.i686 glibc-devel.i686 glibc-devel boost-devel openssl-devel

build:
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make